# Generated by Django 5.1.1 on 2024-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0003_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
