# Generated by Django 5.1.1 on 2024-09-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_api", "0005_alter_vote_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="service_api.employee"
            ),
        ),
    ]
