# Generated by Django 5.1.1 on 2024-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_api", "0006_alter_vote_date_alter_vote_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
