# Generated by Django 5.1.1 on 2024-09-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_api", "0007_alter_vote_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_restaurant_worker",
            field=models.BooleanField(default=False),
        ),
    ]
